Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

def plot_tau(tau, title=""):
    cmap = matplotlib.colors.ListedColormap(["white", 'black'])
    with sns.plotting_context("talk", font_scale=1):
        ax = sns.heatmap()
        ax.set_title("Vertex Assignment Vector")
    f, ax = plt.subplots()
    im = ax.imshow(tau.reshape((1, tau.shape[0])))
    f.colorbar(im, ax=ax)
    f.suptitle(title)
    f.xlabel("Vector")
    return f

n = 100  # number of students

# tau is a column vector of 50 1s followed by 50 2s
tau = np.vstack((np.ones((int(n/2),1)), np.full((int(n/2),1), 2)))


plot_tau(tau)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-f74203679f3b>[0m in [0;36m<module>[0;34m[0m
[1;32m     21[0m [0;34m[0m[0m
[1;32m     22[0m [0;34m[0m[0m
[0;32m---> 23[0;31m [0mplot_tau[0m[0;34m([0m[0mtau[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-5-f74203679f3b>[0m in [0;36mplot_tau[0;34m(tau, title)[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;32mdef[0m [0mplot_tau[0m[0;34m([0m[0mtau[0m[0;34m,[0m [0mtitle[0m[0;34m=[0m[0;34m""[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m     [0mcmap[0m [0;34m=[0m [0mmatplotlib[0m[0;34m.[0m[0mcolors[0m[0;34m.[0m[0mListedColormap[0m[0;34m([0m[0;34m[[0m[0;34m"white"[0m[0;34m,[0m [0;34m'black'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m     [0;32mwith[0m [0msns[0m[0;34m.[0m[0mplotting_context[0m[0;34m([0m[0;34m"talk"[0m[0;34m,[0m [0mfont_scale[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m         [0max[0m [0;34m=[0m [0msns[0m[0;34m.[0m[0mheatmap[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'matplotlib' is not defined
NameError: name 'matplotlib' is not defined

